objects = state1.o state2.o state3.o state4.o state5.o \
	  state6.o state7.o state8.o polling.o video.o \
	  audio.o

CC = /home/sysd7/bin/gcc68s
CFLAGS = -lqcam -I/home/sysd7/source/include

motorola : $(objects)
