objects = /states/motorola/state1.o \
	  /states/motorola/state2.o \
	  /states/motorola/state3.o \
	  /states/motorola/state4.o \
	  /states/motorola/state4.o \
	  /states/motorola/state5.o \
	  /states/motorola/state6.o \
	  /states/motorola/state7.o \
	  /transport/motorola/polling.o \
	  /video/motorola/video.o

CC = /home/sysd7/bin/gcc68s
CFLAGS = -lqcam -I/home/sysd7/source/include

motorola : $(objects)
